version: '2.0'
services: 
  drupal:
    image: drupal:8.8.2
    ports:
      - '8080:80'
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    networks: 
    - drupal_network
  postgres:
    image: postgres:12.1
    environment:
      - POSTGRES_DB=drupal
      - POSTGRES_USER=drupal_user 
      - POSTGRES_PASSWORD=drupal1234
    networks: 
    - drupal_network
networks: 
  drupal_network:


